services:
  prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./metrics-env/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090
      depends_on:
        - client-backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    env_file:
      - ./metrics-env/grafana.env
    depends_on:
      - client-backend
      

  # service-frontend:
  #   build:
  #     context: ./videohub-frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - client-backend

  client-backend:
    build:
      context: ./videohub-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_ADRESS=192.168.0.101
      - SERVER_PORT=8080
      - PSQL_NAME=jdbc:postgresql://service-db/filmsbase
      - STORAGE_DIR=/app
      - LOG_FILENAME=/app/logs.txt
    restart: unless-stopped

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: filmsbase
    volumes:
      - service-db:/var/lib/postgresql/data
    ports:
      - "6000:5432"
    restart: unless-stopped


volumes:
  service-db: