services:
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - 3001:3000
#    env_file:
#      - ../metrics-env/grafana.env
#    depends_on:
#      - prometheus
#
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    volumes:
#      - ../metrics-env/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090

#  kibana:
#    image: kibana:8.6.2
#    container_name: kibana
#    ports:
#      - 5601:5601
#    expose:
#      - "5601"
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
#    depends_on:
#      - elasticsearch

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

#  logstash:
#    user: root
#    image: logstash:8.6.2
#    container_name: logstash
#    ports:
#      - 5044:5044
#    depends_on:
#      - elasticsearch
#      - service-db
#    environment:
#      - PIPELINE_WORKERS=1
#      - PIPELINE_BATCH_SIZE=125
#      - PIPELINE_BATCH_DELAY=50
#    volumes:
#    - ../configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    - ./logstash_data:/usr/share/logstash/data
#    - ./conf/postgresql-42.6.0.jar:/usr/share/logstash/postgresql-42.6.0.jar
#    networks:
#      - videohub-net

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: filmsbase
    volumes:
      - service-db:/var/lib/postgresql/data
    ports:
      - "6000:5432"
    restart: unless-stopped

volumes:
  service-db:
  elasticsearch: